### ISSUE TITLE
Heading 앵커 링크 및 목차(ToC) 지원

### ISSUE THREAD

**Issue by 01-binary** [01-binary/notion-to-jsx#25]
## 개요

Heading 컴포넌트(h1, h2, h3)에 앵커 링크를 추가하여 목차(Table of Contents) 기능과 딥링크를 지원합니다.

## 현재 상태

현재 Heading 컴포넌트는 단순히 텍스트만 렌더링하며, id 속성이나 앵커 링크가 없습니다.

```tsx
// 현재 구현
<h1 className={heading1}>{children}</h1>

// 목표
<h1 id="heading-slug" className={heading1}>
  <a href="#heading-slug" className={anchorLink}>#</a>
  {children}
</h1>
```

### 1. Heading에 id 속성 추가

```typescript
// 텍스트를 slug로 변환
const generateSlug = (text: string): string => {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9가-힣]+/g, '-')
    .replace(/^-|-$/g, '');
};
```

### 2. 앵커 링크 스타일

```css
.anchorLink {
  opacity: 0;
  margin-left: -1.5rem;
  padding-right: 0.5rem;
  transition: opacity 0.2s;
}

h1:hover .anchorLink,
h2:hover .anchorLink,
h3:hover .anchorLink {
  opacity: 0.5;
}
```

### 3. 목차(ToC) 컴포넌트 (선택)

```tsx
interface ToCItem {
  id: string;
  text: string;
  level: 1 | 2 | 3;
}

interface ToCProps {
  blocks: NotionBlock[];
}

const TableOfContents = ({ blocks }: ToCProps) => {
  const headings = extractHeadings(blocks);
  return (
    <nav>
      {headings.map(h => (
        <a key={h.id} href={`#${h.id}`} data-level={h.level}>
          {h.text}
        </a>
      ))}
    </nav>
  );
};
```

## 작업 항목

- [ ] generateSlug 유틸리티 함수 구현
- [ ] Heading 컴포넌트에 id 속성 추가
- [ ] 앵커 링크 아이콘 및 스타일 추가
- [ ] hover 시 앵커 표시 인터랙션
- [ ] (선택) TableOfContents 컴포넌트 구현
- [ ] (선택) 스크롤 시 현재 섹션 하이라이트

## 참고

- GitHub README 스타일 앵커 참고
- Notion 자체 앵커 기능 참고
